services:

  whatsap:
    image: whats_serve_1_0
    container_name: whatsap
    #entrypoint: ["/entrypoint.sh"]
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      WEBHOOK_VERIFY_TOKEN: "diego"
      API_TOKEN: "EAASaXymlIH4BOxuEbezsnC1t5XUIlNCUL3Gm4rFGFayZAcjsRfgeKGRaaaRZA4YPyg87rZCNwERjiAvKsaJ2xtjoOYjGIyMplwePRGoiRftpkzP0ZCBcf6FE3znRw5OWf8xssiS0hjSk9AnNXFBOXFn1Jbiv0Ow0hf5cJVx7Dvf015PKgL2siHgCm2EQS7orf3kIZCWVXyQ4D3ri3zd12oWiHUnF1QQQZD"
      server:port=3000:
      BUSINESS_PHONE: "507682089091988"
      API_VERSION: "v21.0"
      CHATGPT_API_KEY: "sk-svcacct-02fmib7sIV4SRkVnlXoB8DQ2bUBRYmENe5Of8ZmR9uLEAeORPsdJBUsOYmx-5zU7r3T3BlbkFJUJ9KRyQHSHVsRxLLSz07CMrBII6jt_t3nLI-WUFL_tom1WN9WzqMf8nUpPFPDQBNYA"
      IS_CONTAINER: "true"


    restart: always
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh


networks:
  app-network:
    driver: bridge

volumes:
  ollama: