services:

  whatsap:
    image: whats_serve_1_0
    container_name: whatsap
    #entrypoint: ["/entrypoint.sh"]
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      WEBHOOK_VERIFY_TOKEN: "diego"
      API_TOKEN: "EAASaXymlIH4BOwHyqBcQ9KvQyiOgDfspfTpGT1hRdyxZAyfZBLfvYZAQZANnbtbiCeEUdwZAmshk5gE52NL7c6xN9F9oPxb6sZAG21GMiR5P8e0ItsYB6jV54j6ZBhC4Q0gduTqpLmQ84eZCZCwdLiGZBblIsyBAscGglsTWxZA9D9cQNd8kirJaRg4ZAiFuZBQAGAcTmDrxAUMeO1FTfhOJKHKWizpJrp2gZD"
      server:port=3000:
      BUSINESS_PHONE: "507682089091988"
      API_VERSION: "v21.0"
      CHATGPT_API_KEY: "sk-svcacct-02fmib7sIV4SRkVnlXoB8DQ2bUBRYmENe5Of8ZmR9uLEAeORPsdJBUsOYmx-5zU7r3T3BlbkFJUJ9KRyQHSHVsRxLLSz07CMrBII6jt_t3nLI-WUFL_tom1WN9WzqMf8nUpPFPDQBNYA"
      QUYS_CLIENT_ID: "oh_default_front"
      QUYS_CLIENT_SECRET: "KtA0CH1qFCKmk9ggypofHdUQA1DW2SHfK13"
      # QUYS_API_KEY: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJWaUtxWjdSTm5ndE1oVDlFQTlrSUNPa3h6OUk4Z083ZkFuVWZuRnowY3FNIn0.eyJleHAiOjE3MzkyNDk2ODMsImlhdCI6MTczOTI0MjQ4MywiYXV0aF90aW1lIjoxNzM5MjQyNDgxLCJqdGkiOiIwNjdiMGI1NC0zNjNmLTQzNjAtOGJhNC1hNGZlZDQxNmI4ZTUiLCJpc3MiOiJodHRwczovL2F1dGgudWF0Lm9oZWxpdC5uZXQvYXV0aC9yZWFsbXMvdW5pbW9uc2VycmF0ZSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI4YTlhMTRjOC0xYTE4LTQ0NmMtOWNhNS05MzQ1MDFmYjk1OTAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ3ZWJfYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjFkNmY5ZDVjLTI2ZmMtNDA5ZC1iZTZiLTBlMDA4YjM5MTI3YiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJST0xFX0FETUlOX1VOSU1PTiIsIlJPTEVfVVNFUiIsIm9mZmxpbmVfYWNjZXNzIiwiUk9MRV9DSFlfUkVQT19BRE1JTiIsIlJPTEVfQURNSU4iLCJST0xFX0NIWV9ET0NVX0FETUlOIiwiUk9MRV9PQkNfQURNSU4iLCJST0xFX0NIWV9JTlRFX0FETUlOIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiMWQ2ZjlkNWMtMjZmYy00MDlkLWJlNmItMGUwMDhiMzkxMjdiIiwidGVuYW50X2lkIjoyLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInJvbGVzIjpbIlJPTEVfQURNSU5fVU5JTU9OIiwiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJST0xFX0NIWV9SRVBPX0FETUlOIiwiUk9MRV9BRE1JTiIsIlJPTEVfQ0hZX0RPQ1VfQURNSU4iLCJST0xFX09CQ19BRE1JTiIsIlJPTEVfQ0hZX0lOVEVfQURNSU4iLCJST0xFX0FETUlOX1VOSU1PTiIsIlJPTEVfVVNFUiIsIm9mZmxpbmVfYWNjZXNzIiwiUk9MRV9DSFlfUkVQT19BRE1JTiIsIlJPTEVfQURNSU4iLCJST0xFX0NIWV9ET0NVX0FETUlOIiwiUk9MRV9PQkNfQURNSU4iLCJST0xFX0NIWV9JTlRFX0FETUlOIl0sIm5hbWUiOiJEaWVnbyBBbmRyZXMgVG9ycmVzIFJpdmVyb3MiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJkYXRvcnJlc0B1bmltb25zZXJyYXRlLmVkdS5jbyIsImdpdmVuX25hbWUiOiJEaWVnbyBBbmRyZXMiLCJmYW1pbHlfbmFtZSI6IlRvcnJlcyBSaXZlcm9zIiwiZW1haWwiOiJkYXRvcnJlc0B1bmltb25zZXJyYXRlLmVkdS5jbyJ9.P22rv4RlKLnQ6we48o-DEFdTAwYJdaaqyTrtmiQaGSZWPfI1a91CTWPrgDjG1FEWRjh5ZMReInXNDEG6aGCRHOCQ0DWjm5KmHFfbdi38gSjL_fZXSwgabu-RSh5ldzy4NIRY1RwLQr7eOhtI3gu-uN0bpCZjqdl7QSg1VUiNAvXNM_AOGR0AQvFRjyz9qBlYJro-wk3UWCu-Fz8gJK7-TW8Foa9S4dVBRnqrltyU5oGQLrUPevgiYz6WazntFWRLif7lkfy5uRNSU0pt-YLoNp8RtqLIShwVsoM4lPS5Z8C-mPzH5nAFxr952CfyRZ9r5ZD3J0YP-ZVXNcplHxSZCw"
      IS_CONTAINER: "true"


    restart: always
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh


networks:
  app-network:
    driver: bridge

volumes:
  ollama: