spring.application.name=demoChat2
server.port=3000

WEBHOOK_VERIFY_TOKEN=diego
BUSINESS_PHONE=507682089091988
API_TOKEN=EAASaXymlIH4BO7bhZBj1nEpsbOrivqEoEfff6BB5btlEIdF3HUxsajyrxoJ6u8ZACsX9mXPqARh4360AylrKp1G4RvNLLSjpU708YcZBajdATDZAbqbZBZB8nE90ZAMZASUcWhxnZCttvfdmVnTukLoVhZC3WcxZBpCa9HHerZCo1fVp3GoHEGXzM56TgR8pDDduAeX3mO26PP7ISZAtmGQkZBFJjTKJjdkf4ZD
API_VERSION=v21.0
CHATGPT_API_KEY=sk-svcacct-02fmib7sIV4SRkVnlXoB8DQ2bUBRYmENe5Of8ZmR9uLEAeORPsdJBUsOYmx-5zU7r3T3BlbkFJUJ9KRyQHSHVsRxLLSz07CMrBII6jt_t3nLI-WUFL_tom1WN9WzqMf8nUpPFPDQBNYA
IS_CONTAINER=true
QUYS_CLIENT_ID=oh_default_front
QUYS_CLIENT_SECRET=KtA0CH1qFCKmk9ggypofHdUQA1DW2SHfK13
QUYS_API_FETCH_URL=https://auth.uat.ohelit.net/auth/realms/unimonserrate/protocol/openid-connect/token
