spring.application.name=demoChat2
server.port=3000

WEBHOOK_VERIFY_TOKEN=diego
BUSINESS_PHONE=507682089091988
API_TOKEN=EAASaXymlIH4BO7dC5mQgY2ZBc2fEibKhqRDn6KgrkBSZBkbwFoFZAsorH8TI7otnNsq6J6Kq77vylrdyTNYgx8WZA8PFfCcd8QnbGIFL0Cxl2fkwaZBZAyhEHdvrINWfHRGaUfI6PznjXGTvkyV1ZArvBYk3bYtOBIipsGciS9qp8VvNsG0rY5gZATfFrbqbAPErfYW6xHxX5ZAvVWcNfnkq96atyQEMZD
API_VERSION=v21.0
CHATGPT_API_KEY=sk-svcacct-02fmib7sIV4SRkVnlXoB8DQ2bUBRYmENe5Of8ZmR9uLEAeORPsdJBUsOYmx-5zU7r3T3BlbkFJUJ9KRyQHSHVsRxLLSz07CMrBII6jt_t3nLI-WUFL_tom1WN9WzqMf8nUpPFPDQBNYA
IS_CONTAINER=true
QUYS_CLIENT_ID=oh_default_front
QUYS_CLIENT_SECRET=KtA0CH1qFCKmk9ggypofHdUQA1DW2SHfK13
QUYS_API_FETCH_URL=https://auth.uat.ohelit.net/auth/realms/unimonserrate/protocol/openid-connect/token
