spring.application.name=demoChat2
server.port=3000

WEBHOOK_VERIFY_TOKEN=diego
BUSINESS_PHONE=507682089091988
API_TOKEN=EAASaXymlIH4BO3dtuDlG7NK4rY6mc1uoHoc6aNg0iTIB8mNQfzBQZA3JMMhL7ugoYDu7ZBhylTzOnnJBYd2GPS2GTfVqXrcWljnaB8q9h8ZBAupOFIQVdwn3PEU9PKbMArQzxSqnzCMN6TDR2rRaW6IcaGJkGMZASHKUz6Tf2dbY5EyxQGz7slVnnov3r40MrKw44FKLEkoU1KxtZBO1DJYMWVCwZD
API_VERSION=v21.0
CHATGPT_API_KEY=sk-svcacct-02fmib7sIV4SRkVnlXoB8DQ2bUBRYmENe5Of8ZmR9uLEAeORPsdJBUsOYmx-5zU7r3T3BlbkFJUJ9KRyQHSHVsRxLLSz07CMrBII6jt_t3nLI-WUFL_tom1WN9WzqMf8nUpPFPDQBNYA
IS_CONTAINER=true
QUYS_CLIENT_ID=oh_default_front
QUYS_CLIENT_SECRET=KtA0CH1qFCKmk9ggypofHdUQA1DW2SHfK13
QUYS_API_FETCH_URL=https://auth.uat.ohelit.net/auth/realms/unimonserrate/protocol/openid-connect/token
